FROM python:3.10-slim
RUN apt-get update && apt-get install -y python3-tk
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Команда за замовчуванням (контейнер просто збереться, що нам і треба)
CMD ["python", "LR4.py"]
